accent = "#BCCD80"
cursor = "#FBFCF7"
foreground = "#FBFCF6"
background = "#1D211A"
selection_foreground = "#FBFCF6"
selection_background = "#616B5C"

color0 = "#1D211A"
color1 = "#EA938B"
color2 = "#BCCD80"
color3 = "#F7C775"
color4 = "#90DDE4"
color5 = "#DAC3ED"
color6 = "#A5D6CB"
color7 = "#FBFCF6"
color8 = "#99A293"
color9 = "#EA938B"
color10 = "#ECF6AE"
color11 = "#FBE09F"
color12 = "#90DDE4"
color13 = "#DAC3ED"
color14 = "#A5D6CB"
color15 = "#FBFCF7"
